# Generated by Django 5.2.11 on 2026-03-24 00:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0003_order_is_recurring_instance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('stuart', 'Stuart')], default='stuart', max_length=40)),
                ('provider_reference', models.CharField(blank=True, db_index=True, max_length=120)),
                ('package_reference', models.CharField(blank=True, db_index=True, max_length=120)),
                ('client_reference', models.CharField(blank=True, db_index=True, max_length=120)),
                ('status', models.CharField(choices=[('created', 'Created'), ('assigned', 'Assigned'), ('waiting_pickup', 'Waiting Pickup'), ('picking_up', 'Picking Up'), ('picked_up', 'Picked Up'), ('delivering', 'Delivering'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('failed', 'Failed'), ('unknown', 'Unknown')], default='unknown', max_length=40)),
                ('tracking_url', models.URLField(blank=True)),
                ('client_tracking_url', models.URLField(blank=True)),
                ('eta_to_dropoff', models.DateTimeField(blank=True, null=True)),
                ('courier_name', models.CharField(blank=True, max_length=255)),
                ('courier_phone', models.CharField(blank=True, max_length=50)),
                ('courier_transport_type', models.CharField(blank=True, max_length=100)),
                ('last_courier_latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('last_courier_longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('pickup_address_snapshot', models.JSONField(blank=True, default=dict)),
                ('dropoff_address_snapshot', models.JSONField(blank=True, default=dict)),
                ('quote_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('quote_currency', models.CharField(blank=True, max_length=3)),
                ('last_error', models.CharField(blank=True, max_length=255)),
                ('test_mode', models.BooleanField(default=True)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sub_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_jobs', to='orders.producersuborder')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_event_id', models.CharField(blank=True, db_index=True, max_length=120)),
                ('event_type', models.CharField(blank=True, max_length=120)),
                ('normalized_status', models.CharField(blank=True, max_length=40)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('delivery_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='delivery.deliveryjob')),
            ],
            options={
                'ordering': ['-received_at', '-id'],
            },
        ),
    ]
