# Generated by Django 5.2.11 on 2026-03-09 18:14

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_customerprofile_user_alter_producer_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_recurring_instance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='recurring_scheduled_for',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='special_instructions',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='RecurringOrderTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(choices=[('weekly', 'Weekly'), ('fortnightly', 'Fortnightly')], default='weekly', max_length=20)),
                ('order_day', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)])),
                ('delivery_day', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)])),
                ('next_order_date', models.DateField()),
                ('delivery_address', models.TextField()),
                ('customer_postcode', models.CharField(max_length=12)),
                ('payment_method', models.CharField(blank=True, default='test_card', max_length=50)),
                ('is_paused', models.BooleanField(default=False)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('last_generated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_order_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecurringOrderInstanceOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_order_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_recurring_overrides', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instance_overrides', to='orders.recurringordertemplate')),
            ],
            options={
                'ordering': ['-scheduled_order_date', '-id'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='recurring_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_orders', to='orders.recurringordertemplate'),
        ),
        migrations.CreateModel(
            name='RecurringOrderTemplateItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_quantity', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recurring_template_items', to='orders.product')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.recurringordertemplate')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='UserNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default='general', max_length=50)),
                ('message', models.CharField(max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecurringOrderInstanceOverrideItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('override', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.recurringorderinstanceoverride')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recurring_override_items', to='orders.product')),
            ],
            options={
                'ordering': ['id'],
                'constraints': [models.UniqueConstraint(fields=('override', 'product'), name='orders_unique_override_product')],
            },
        ),
        migrations.AddConstraint(
            model_name='recurringorderinstanceoverride',
            constraint=models.UniqueConstraint(fields=('template', 'scheduled_order_date'), name='orders_unique_template_override_per_date'),
        ),
        migrations.AddConstraint(
            model_name='recurringordertemplateitem',
            constraint=models.UniqueConstraint(fields=('template', 'product'), name='orders_unique_template_product'),
        ),
    ]
