"""
Django settings for bristol_marketplace project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import importlib.util
import os
from datetime import timedelta
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-u0vs+6_)3(@t(&fyk26a%giotb0_ij8p@zm=t#qd79_m_4ef9@'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DJANGO_DEBUG", "true").lower() in {"1", "true", "yes", "on"}

ALLOWED_HOSTS = [
    host.strip()
    for host in os.getenv("DJANGO_ALLOWED_HOSTS", "127.0.0.1,localhost,0.0.0.0,testserver,.trycloudflare.com").split(",")
    if host.strip()
]

# Application definition
HAS_CORSHEADERS = importlib.util.find_spec("corsheaders") is not None
HAS_SIMPLEJWT = importlib.util.find_spec("rest_framework_simplejwt") is not None

# Installed apps are grouped by responsibility:
# - Django defaults
# - third-party API/auth support
# - marketplace domain apps under `apps.*`
INSTALLED_APPS = [
    # Django default apps
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    # Third-party
    "rest_framework",

    # Your apps
    "apps.accounts",
    "apps.catalog",
    "apps.orders",
    "apps.geo",
    "apps.producer_portal",
    "apps.payments",
    "apps.delivery",
    "apps.community",
    "apps.content",
]

if HAS_CORSHEADERS:
    INSTALLED_APPS.insert(6, "corsheaders")

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

if HAS_CORSHEADERS:
    MIDDLEWARE.insert(1, 'corsheaders.middleware.CorsMiddleware')

ROOT_URLCONF = 'bristol_marketplace.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'bristol_marketplace.wsgi.application'

# Active runtime database configuration. In Docker this points to PostgreSQL;
# local defaults are also set up for the containerized database service.
DATABASES = {
    "default": {
        "ENGINE": os.getenv("DJANGO_DB_ENGINE", "django.db.backends.postgresql"),
        "NAME": os.getenv("DJANGO_DB_NAME", "bristol_marketplace"),
        "USER": os.getenv("DJANGO_DB_USER", "postgres"),
        "PASSWORD": os.getenv("DJANGO_DB_PASSWORD", "postgres"),
        "HOST": os.getenv("DJANGO_DB_HOST", "db"),
        "PORT": os.getenv("DJANGO_DB_PORT", "5432"),
    }
}

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {'min_length': 10},
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_DIRS = [
    BASE_DIR / "DESD" / "dist",
]
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# Vite frontend output location used by Django's SPA-serving view.
FRONTEND_DIST_DIR = BASE_DIR / "DESD" / "dist"

AUTH_USER_MODEL = "accounts.User"

FRONTEND_URL = os.getenv("FRONTEND_URL", "http://127.0.0.1:8000")
STRIPE_PUBLISHABLE_KEY = os.getenv("STRIPE_PUBLISHABLE_KEY", "")
STRIPE_SECRET_KEY = os.getenv("STRIPE_SECRET_KEY", "")
STRIPE_WEBHOOK_SECRET = os.getenv("STRIPE_WEBHOOK_SECRET", "")
PAYMENT_SERVICE_BASE_URL = os.getenv("PAYMENT_SERVICE_BASE_URL", "http://payments:8010")
PAYMENT_SERVICE_SHARED_SECRET = os.getenv("PAYMENT_SERVICE_SHARED_SECRET", "local-payment-service-secret")
PAYMENT_SERVICE_TIMEOUT_SECONDS = int(os.getenv("PAYMENT_SERVICE_TIMEOUT_SECONDS", "15"))
STUART_SERVICE_BASE_URL = os.getenv("STUART_SERVICE_BASE_URL", "http://stuart:8020")
STUART_SERVICE_SHARED_SECRET = os.getenv("STUART_SERVICE_SHARED_SECRET", "local-stuart-service-secret")
STUART_SERVICE_TIMEOUT_SECONDS = int(os.getenv("STUART_SERVICE_TIMEOUT_SECONDS", "15"))
STUART_WEBHOOK_SECRET = os.getenv("STUART_WEBHOOK_SECRET", "")
DELIVERY_SIMULATION_ENABLED = os.getenv("DELIVERY_SIMULATION_ENABLED", "true").lower() in {"1", "true", "yes", "on"}
DELIVERY_SIMULATION_TOTAL_SECONDS = int(os.getenv("DELIVERY_SIMULATION_TOTAL_SECONDS", "120"))
DELIVERY_SIMULATION_POLL_SECONDS = int(os.getenv("DELIVERY_SIMULATION_POLL_SECONDS", "15"))
STRIPE_SUCCESS_URL = os.getenv(
    "STRIPE_SUCCESS_URL",
    f"{FRONTEND_URL.rstrip('/')}/checkout/success?session_id={{CHECKOUT_SESSION_ID}}",
)
STRIPE_CANCEL_URL = os.getenv(
    "STRIPE_CANCEL_URL",
    f"{FRONTEND_URL.rstrip('/')}/checkout/cancel",
)
JWT_ACCESS_TOKEN_MINUTES = int(os.getenv("JWT_ACCESS_TOKEN_MINUTES", "15"))
JWT_DEFAULT_REFRESH_DAYS = int(os.getenv("JWT_DEFAULT_REFRESH_DAYS", "1"))
JWT_REMEMBER_ME_REFRESH_DAYS = int(os.getenv("JWT_REMEMBER_ME_REFRESH_DAYS", "30"))
JWT_DEFAULT_REFRESH_LIFETIME = timedelta(days=JWT_DEFAULT_REFRESH_DAYS)
JWT_REMEMBER_ME_REFRESH_LIFETIME = timedelta(days=JWT_REMEMBER_ME_REFRESH_DAYS)

EMAIL_VERIFICATION_TOKEN_MAX_AGE = int(os.getenv("EMAIL_VERIFICATION_TOKEN_MAX_AGE", "86400"))
PASSWORD_RESET_TOKEN_MAX_AGE = int(os.getenv("PASSWORD_RESET_TOKEN_MAX_AGE", "1800"))


def _optional_env(name: str, default: str = "") -> str:
    value = os.getenv(name)
    if value is None or not value.strip():
        return default
    return value


ACCOUNT_EMAIL_SUPPRESS_DOMAINS = _optional_env(
    "ACCOUNT_EMAIL_SUPPRESS_DOMAINS",
    "example.com,example.org,example.net,invalid,localhost,local,localfood.test,test",
)
ACCOUNT_EMAIL_SUPPRESS_LOCAL_PARTS = _optional_env(
    "ACCOUNT_EMAIL_SUPPRESS_LOCAL_PARTS",
    "dummy,example,fake,test",
)

SMTP_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
CONSOLE_BACKEND = "django.core.mail.backends.console.EmailBackend"
REQUESTED_EMAIL_BACKEND = os.getenv("EMAIL_BACKEND", CONSOLE_BACKEND)

EMAIL_HOST = os.getenv("EMAIL_HOST", "")
EMAIL_PORT = int(os.getenv("EMAIL_PORT", "587"))
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD", "")
EMAIL_USE_TLS = os.getenv("EMAIL_USE_TLS", "true").lower() in {"1", "true", "yes", "on"}
EMAIL_USE_SSL = os.getenv("EMAIL_USE_SSL", "false").lower() in {"1", "true", "yes", "on"}
DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL", "noreply@localfood.test")

smtp_config_present = bool(EMAIL_HOST and EMAIL_HOST_USER and EMAIL_HOST_PASSWORD)
if REQUESTED_EMAIL_BACKEND == SMTP_BACKEND and not smtp_config_present:
    EMAIL_BACKEND = CONSOLE_BACKEND
else:
    EMAIL_BACKEND = REQUESTED_EMAIL_BACKEND

# DRF configuration controls authentication behaviour and abuse-prevention
# throttles for sensitive endpoints such as registration and login.
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        (
            "rest_framework_simplejwt.authentication.JWTAuthentication",
            "rest_framework.authentication.BasicAuthentication",
            "rest_framework.authentication.SessionAuthentication",
        )
        if HAS_SIMPLEJWT
        else (
            "rest_framework.authentication.BasicAuthentication",
            "rest_framework.authentication.SessionAuthentication",
        )
    ),
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.AllowAny",
    ),
    "DEFAULT_THROTTLE_RATES": {
        "anon": os.getenv("DRF_THROTTLE_ANON", "50/hour"),
        "user": os.getenv("DRF_THROTTLE_USER", "250/hour"),
        "register_anon": os.getenv("DRF_THROTTLE_REGISTER_ANON", "10/hour"),
        "register_user": os.getenv("DRF_THROTTLE_REGISTER_USER", "20/hour"),
        "login_anon": os.getenv("DRF_THROTTLE_LOGIN_ANON", "10/minute"),
        "login_user": os.getenv("DRF_THROTTLE_LOGIN_USER", "30/minute"),
    },
}

if HAS_SIMPLEJWT:
    SIMPLE_JWT = {
        "ACCESS_TOKEN_LIFETIME": timedelta(minutes=JWT_ACCESS_TOKEN_MINUTES),
        "REFRESH_TOKEN_LIFETIME": JWT_DEFAULT_REFRESH_LIFETIME,
        "AUTH_HEADER_TYPES": ("Bearer",),
        "UPDATE_LAST_LOGIN": True,
    }

CORS_ALLOWED_ORIGINS = [
    origin.strip()
    for origin in os.getenv(
        "CORS_ALLOWED_ORIGINS",
        "http://localhost:8000,http://127.0.0.1:8000,http://localhost:5173,http://127.0.0.1:5173,http://localhost:3000,http://127.0.0.1:3000",
    ).split(",")
    if origin.strip()
]
CORS_ALLOW_CREDENTIALS = True

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
        },
    },
    "loggers": {
        "apps.accounts.auth": {
            "handlers": ["console"],
            "level": os.getenv("ACCOUNTS_AUTH_LOG_LEVEL", "INFO"),
            "propagate": False,
        },
        "apps.accounts.email": {
            "handlers": ["console"],
            "level": os.getenv("ACCOUNTS_EMAIL_LOG_LEVEL", "INFO"),
            "propagate": False,
        },
    },
}
