# Generated by Django 5.2.11 on 2026-02-26 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="producerprofile",
            name="contact_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
