from datetime import date, timedelta
from decimal import Decimal

from django.core.management.base import BaseCommand
from django.utils import timezone

from apps.catalog.models import Category, Producer, Product
from apps.community.models import ProductReview


class Command(BaseCommand):
    help = "Seed demo catalog, compliance, and review data for Sprint 1."

    def handle(self, *args, **options):
        categories_payload = [
            {"name": "Vegetables", "slug": "vegetables"},
            {"name": "Dairy Products", "slug": "dairy"},
            {"name": "Bakery", "slug": "bakery"},
            {"name": "Preserves", "slug": "preserves"},
            {"name": "Fruit", "slug": "fruit"},
        ]

        categories: dict[str, Category] = {}
        for payload in categories_payload:
            category, _ = Category.objects.update_or_create(
                slug=payload["slug"], defaults={"name": payload["name"]}
            )
            categories[category.slug] = category

        producers_payload = [
            {
                "name": "Green Valley Farm",
                "location": "Kent, UK",
                "description": "Family-run farm focused on seasonal vegetables.",
                "delivery_lead_time": 48,
                "postcode": "ME13 8XY",
                "latitude": Decimal("51.278700"),
                "longitude": Decimal("0.521700"),
            },
            {
                "name": "Sunrise Dairy",
                "location": "Devon, UK",
                "description": "Small-batch dairy from grass-fed herds.",
                "delivery_lead_time": 72,
                "postcode": "EX1 1AA",
                "latitude": Decimal("50.718400"),
                "longitude": Decimal("-3.533900"),
            },
            {
                "name": "Harbor Bakery",
                "location": "Bristol, UK",
                "description": "Local sourdough and baked goods made daily.",
                "delivery_lead_time": 48,
                "postcode": "BS1 5TR",
                "latitude": Decimal("51.454500"),
                "longitude": Decimal("-2.587900"),
            },
            {
                "name": "Orchard Hill",
                "location": "Somerset, UK",
                "description": "Seasonal fruit and preserves from local orchards.",
                "delivery_lead_time": 48,
                "postcode": "BA1 1AA",
                "latitude": Decimal("51.153700"),
                "longitude": Decimal("-2.998800"),
            },
        ]

        producers: dict[str, Producer] = {}
        for payload in producers_payload:
            producer, _ = Producer.objects.update_or_create(
                name=payload["name"],
                defaults={
                    "location": payload["location"],
                    "description": payload["description"],
                    "delivery_lead_time": payload["delivery_lead_time"],
                    "postcode": payload["postcode"],
                    "latitude": payload["latitude"],
                    "longitude": payload["longitude"],
                },
            )
            producers[producer.name] = producer

        now = timezone.now()
        products_payload = [
            {
                "name": "Organic Tomatoes",
                "description": "Vine-ripened organic tomatoes harvested for peak flavour.",
                "price": Decimal("4.50"),
                "unit": Product.Unit.KG,
                "producer_name": "Green Valley Farm",
                "category_slug": "vegetables",
                "harvest_date": date(2026, 2, 14),
                "availability": Product.Availability.IN_SEASON,
                "seasonal_dates": "January - March",
                "is_organic": True,
                "organic_certification": "Soil Association",
                "allergens": [],
                "image_url": "https://images.unsplash.com/photo-1546094096-0df4bcaaa337?w=800",
                "stock": 50,
                "food_miles": 12,
                "storage_tips": "Store at room temperature and use within one week.",
                "recipe_ideas": ["Caprese salad", "Roasted tomato soup"],
            },
            {
                "name": "Organic Kale",
                "description": "Dark leafy organic kale suitable for soups and salads.",
                "price": Decimal("1.75"),
                "unit": Product.Unit.KG,
                "producer_name": "Green Valley Farm",
                "category_slug": "vegetables",
                "harvest_date": date(2026, 2, 15),
                "availability": Product.Availability.IN_SEASON,
                "seasonal_dates": "October - March",
                "is_organic": True,
                "organic_certification": "Soil Association",
                "allergens": [],
                "image_url": "https://images.unsplash.com/photo-1590777516009-c162e90e4b86?w=800",
                "stock": 40,
                "food_miles": 12,
                "is_surplus": True,
                "surplus_discount": 30,
                "surplus_original_price": Decimal("2.50"),
                "surplus_expires_at": now + timedelta(hours=36),
                "surplus_best_before": "3 days",
                "storage_tips": "Keep chilled and rinse immediately before use.",
                "recipe_ideas": ["Kale and bean stew", "Green smoothie"],
            },
            {
                "name": "Baby Spinach",
                "description": "Tender organic spinach leaves for salads and smoothies.",
                "price": Decimal("2.10"),
                "unit": Product.Unit.KG,
                "producer_name": "Green Valley Farm",
                "category_slug": "vegetables",
                "harvest_date": date(2026, 2, 13),
                "availability": Product.Availability.IN_SEASON,
                "seasonal_dates": "January - April",
                "is_organic": True,
                "organic_certification": "Organic Farmers & Growers",
                "allergens": [],
                "image_url": "https://images.unsplash.com/photo-1576045057995-568f588f82fb?w=800",
                "stock": 32,
                "food_miles": 12,
                "storage_tips": "Keep chilled and use within 3 days.",
                "recipe_ideas": ["Spinach salad", "Green smoothie"],
            },
            {
                "name": "Heritage Carrots",
                "description": "Sweet mixed-colour carrots grown locally.",
                "price": Decimal("1.90"),
                "unit": Product.Unit.KG,
                "producer_name": "Green Valley Farm",
                "category_slug": "vegetables",
                "harvest_date": date(2026, 2, 12),
                "availability": Product.Availability.YEAR_ROUND,
                "seasonal_dates": "",
                "is_organic": False,
                "organic_certification": "",
                "allergens": [],
                "image_url": "https://images.unsplash.com/photo-1598170845058-32b9d6a5da37?w=800",
                "stock": 70,
                "food_miles": 12,
                "storage_tips": "Store in a cool, dry place.",
                "recipe_ideas": ["Roasted carrots", "Carrot soup"],
            },
            {
                "name": "Root Potatoes",
                "description": "All-purpose potatoes for roasting, mashing, and baking.",
                "price": Decimal("1.40"),
                "unit": Product.Unit.KG,
                "producer_name": "Green Valley Farm",
                "category_slug": "vegetables",
                "harvest_date": date(2026, 2, 10),
                "availability": Product.Availability.YEAR_ROUND,
                "seasonal_dates": "",
                "is_organic": False,
                "organic_certification": "",
                "allergens": [],
                "image_url": "https://images.unsplash.com/photo-1518977676601-b53f82aba655?w=800",
                "stock": 120,
                "food_miles": 12,
                "storage_tips": "Store in a dark, cool cupboard.",
                "recipe_ideas": ["Mashed potatoes", "Oven wedges"],
            },
            {
                "name": "Fresh Whole Milk",
                "description": "Whole milk from grass-fed cows.",
                "price": Decimal("2.80"),
                "unit": Product.Unit.LITRE,
                "producer_name": "Sunrise Dairy",
                "category_slug": "dairy",
                "harvest_date": date(2026, 2, 15),
                "availability": Product.Availability.YEAR_ROUND,
                "seasonal_dates": "",
                "is_organic": False,
                "organic_certification": "",
                "allergens": ["Milk"],
                "image_url": "https://images.unsplash.com/photo-1550583724-b2692b85b150?w=800",
                "stock": 100,
                "food_miles": 45,
                "storage_tips": "Keep refrigerated and consume within 3 days of opening.",
                "recipe_ideas": ["Porridge", "Homemade yogurt"],
            },
            {
                "name": "Cheddar Cheese",
                "description": "Mature cheddar with a rich and nutty flavour.",
                "price": Decimal("6.90"),
                "unit": Product.Unit.KG,
                "producer_name": "Sunrise Dairy",
                "category_slug": "dairy",
                "harvest_date": date(2026, 2, 13),
                "availability": Product.Availability.YEAR_ROUND,
                "seasonal_dates": "",
                "is_organic": False,
                "organic_certification": "",
                "allergens": ["Milk"],
                "image_url": "https://images.unsplash.com/photo-1452195100486-9cc805987862?w=800",
                "stock": 30,
                "food_miles": 45,
                "storage_tips": "Keep refrigerated and sealed.",
                "recipe_ideas": ["Cheese toastie", "Cheese tart"],
            },
            {
                "name": "Organic Greek Yogurt",
                "description": "Organic strained yogurt with live cultures.",
                "price": Decimal("3.60"),
                "unit": Product.Unit.EACH,
                "producer_name": "Sunrise Dairy",
                "category_slug": "dairy",
                "harvest_date": date(2026, 2, 14),
                "availability": Product.Availability.YEAR_ROUND,
                "seasonal_dates": "",
                "is_organic": True,
                "organic_certification": "Soil Association",
                "allergens": ["Milk"],
                "image_url": "https://images.unsplash.com/photo-1488477181946-6428a0291777?w=800",
                "stock": 42,
                "food_miles": 45,
                "storage_tips": "Refrigerate and consume within 4 days of opening.",
                "recipe_ideas": ["Yogurt bowl", "Tzatziki"],
            },
            {
                "name": "Sourdough Bread",
                "description": "Crusty sourdough loaf baked this morning.",
                "price": Decimal("2.80"),
                "unit": Product.Unit.EACH,
                "producer_name": "Harbor Bakery",
                "category_slug": "bakery",
                "harvest_date": date(2026, 2, 16),
                "availability": Product.Availability.YEAR_ROUND,
                "seasonal_dates": "",
                "is_organic": False,
                "organic_certification": "",
                "allergens": ["Wheat (Gluten)"],
                "image_url": "https://images.unsplash.com/photo-1549931319-a545dcf3bc73?w=800",
                "stock": 20,
                "food_miles": 9,
                "is_surplus": True,
                "surplus_discount": 20,
                "surplus_original_price": Decimal("3.50"),
                "surplus_expires_at": now + timedelta(hours=20),
                "surplus_best_before": "1 day",
                "storage_tips": "Best eaten same day. Freeze slices for later use.",
                "recipe_ideas": ["French toast", "Open sandwiches"],
            },
            {
                "name": "Walnut Bread",
                "description": "Dense artisan loaf with toasted walnuts.",
                "price": Decimal("3.40"),
                "unit": Product.Unit.EACH,
                "producer_name": "Harbor Bakery",
                "category_slug": "bakery",
                "harvest_date": date(2026, 2, 16),
                "availability": Product.Availability.YEAR_ROUND,
                "seasonal_dates": "",
                "is_organic": False,
                "organic_certification": "",
                "allergens": ["Wheat (Gluten)", "Nuts (Walnuts)"],
                "image_url": "https://images.unsplash.com/photo-1509440159596-0249088772ff?w=800",
                "stock": 18,
                "food_miles": 9,
                "storage_tips": "Keep in a bread box and consume within 2 days.",
                "recipe_ideas": ["Cheese board slices", "Toast with butter"],
            },
            {
                "name": "Strawberry Jam",
                "description": "Small-batch organic strawberry preserve.",
                "price": Decimal("4.20"),
                "unit": Product.Unit.EACH,
                "producer_name": "Orchard Hill",
                "category_slug": "preserves",
                "harvest_date": date(2026, 2, 9),
                "availability": Product.Availability.YEAR_ROUND,
                "seasonal_dates": "",
                "is_organic": True,
                "organic_certification": "Organic Farmers & Growers",
                "allergens": ["Sulphites"],
                "image_url": "https://images.unsplash.com/photo-1599490659213-e2b9527bd087?w=800",
                "stock": 55,
                "food_miles": 28,
                "storage_tips": "Refrigerate after opening.",
                "recipe_ideas": ["Toast topping", "Cake filling"],
            },
            {
                "name": "Fresh Apples",
                "description": "Crisp dessert apples with balanced sweetness.",
                "price": Decimal("3.00"),
                "unit": Product.Unit.KG,
                "producer_name": "Orchard Hill",
                "category_slug": "fruit",
                "harvest_date": date(2026, 2, 11),
                "availability": Product.Availability.YEAR_ROUND,
                "seasonal_dates": "",
                "is_organic": False,
                "organic_certification": "",
                "allergens": [],
                "image_url": "https://images.unsplash.com/photo-1567306226416-28f0efdc88ce?w=800",
                "stock": 75,
                "food_miles": 28,
                "storage_tips": "Keep chilled for best shelf life.",
                "recipe_ideas": ["Apple slices", "Fruit salad"],
            },
            {
                "name": "Summer Strawberries",
                "description": "Organic strawberries at peak summer sweetness.",
                "price": Decimal("4.80"),
                "unit": Product.Unit.KG,
                "producer_name": "Orchard Hill",
                "category_slug": "fruit",
                "harvest_date": date(2025, 7, 10),
                "availability": Product.Availability.IN_SEASON,
                "seasonal_dates": "June - August",
                "is_organic": True,
                "organic_certification": "Soil Association",
                "allergens": [],
                "image_url": "https://images.unsplash.com/photo-1464965911861-746a04b4bca6?w=800",
                "stock": 22,
                "food_miles": 28,
                "storage_tips": "Keep refrigerated and consume quickly.",
                "recipe_ideas": ["Fruit parfait", "Strawberry compote"],
            },
        ]

        products: dict[str, Product] = {}
        for payload in products_payload:
            producer = producers[payload["producer_name"]]
            category = categories[payload["category_slug"]]
            product, _ = Product.objects.update_or_create(
                name=payload["name"],
                producer=producer,
                defaults={
                    "description": payload["description"],
                    "price": payload["price"],
                    "unit": payload["unit"],
                    "category": category,
                    "harvest_date": payload["harvest_date"],
                    "availability": payload["availability"],
                    "seasonal_dates": payload["seasonal_dates"],
                    "is_organic": payload["is_organic"],
                    "organic_certification": payload["organic_certification"],
                    "allergens": payload["allergens"],
                    "image_url": payload["image_url"],
                    "stock": payload["stock"],
                    "food_miles": payload["food_miles"],
                    "is_surplus": payload.get("is_surplus", False),
                    "surplus_discount": payload.get("surplus_discount"),
                    "surplus_original_price": payload.get("surplus_original_price"),
                    "surplus_expires_at": payload.get("surplus_expires_at"),
                    "surplus_best_before": payload.get("surplus_best_before", ""),
                    "storage_tips": payload.get("storage_tips", ""),
                    "recipe_ideas": payload.get("recipe_ideas", []),
                },
            )
            products[product.name] = product

        reviews_payload = [
            {
                "product_name": "Organic Tomatoes",
                "reviewer_name": "Jane Customer",
                "rating": 5,
                "comment": "Great flavour and freshness.",
                "verified_purchase": True,
            },
            {
                "product_name": "Cheddar Cheese",
                "reviewer_name": "Community Kitchen",
                "rating": 4,
                "comment": "Consistent quality for weekly deliveries.",
                "verified_purchase": False,
            },
            {
                "product_name": "Walnut Bread",
                "reviewer_name": "The Green Table Restaurant",
                "rating": 5,
                "comment": "Excellent crust and texture.",
                "verified_purchase": False,
            },
        ]

        for payload in reviews_payload:
            ProductReview.objects.update_or_create(
                product=products[payload["product_name"]],
                reviewer_name=payload["reviewer_name"],
                comment=payload["comment"],
                defaults={
                    "rating": payload["rating"],
                    "verified_purchase": payload["verified_purchase"],
                },
            )

        self.stdout.write(self.style.SUCCESS("Demo catalog seed complete."))
