# Generated by Django 5.2.11 on 2026-04-24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0001_initial"),
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GeneratedContentSuggestion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("content_type", models.CharField(choices=[("recipe", "Recipe"), ("story", "Farm story")], max_length=20)),
                ("prompt_context", models.JSONField(blank=True, default=dict)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("ingredients", models.TextField(blank=True)),
                ("instructions", models.TextField(blank=True)),
                ("body", models.TextField(blank=True)),
                ("seasonal_tag", models.CharField(blank=True, max_length=50)),
                ("status", models.CharField(choices=[("saved", "Saved"), ("used", "Used")], default="saved", max_length=20)),
                (
                    "ai_disclosure",
                    models.CharField(
                        default="Generated with Vertex AI for producer review before publishing.",
                        max_length=255,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "producer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generated_content_suggestions",
                        to="orders.producer",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="generatedcontentsuggestion",
            name="products",
            field=models.ManyToManyField(
                blank=True, related_name="generated_content_suggestions", to="orders.product"
            ),
        ),
    ]
