# Generated by Django 5.2.11 on 2026-05-05 04:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModerationReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(choices=[('customer_account', 'Customer account'), ('producer_account', 'Producer account'), ('product', 'Product'), ('review', 'Review'), ('recipe', 'Recipe'), ('farm_story', 'Farm story')], max_length=40)),
                ('object_id', models.PositiveIntegerField()),
                ('reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('kept', 'Kept'), ('removed', 'Removed')], default='open', max_length=20)),
                ('removed_at', models.DateTimeField(blank=True, null=True)),
                ('kept_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_note', models.TextField(blank=True)),
                ('target_snapshot', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_reports_submitted', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_reports_resolved', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['target_type', 'status'], name='moderation__target__ee648c_idx'), models.Index(fields=['content_type', 'object_id', 'status'], name='moderation__content_192b5c_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'open')), fields=('content_type', 'object_id', 'reported_by', 'status'), name='unique_open_report_per_user_target')],
            },
        ),
    ]
