# Generated by Django 5.2.11 on 2026-05-07 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_settlement_marketplace_suborders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklysettlement',
            name='status',
            field=models.CharField(choices=[('pending_bank_transfer', 'Pending Bank Transfer'), ('processing', 'Processing'), ('processed', 'Processed'), ('paid', 'Paid'), ('failed', 'Failed')], default='pending_bank_transfer', max_length=24),
        ),
    ]
