# Generated by Django 5.2.11 on 2026-05-07 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producer_portal', '0006_product_certification_surplus_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='producerproduct',
            name='no_known_allergens_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
