# Generated by Django 5.2.11 on 2026-02-24 13:31

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True)),
                ("slug", models.SlugField(max_length=120, unique=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Producer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=160, unique=True)),
                ("location", models.CharField(max_length=160)),
                ("description", models.TextField(blank=True)),
                ("delivery_lead_time", models.PositiveIntegerField(default=48)),
                ("postcode", models.CharField(blank=True, max_length=20)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("price", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("kg", "Kilogram"),
                            ("litre", "Litre"),
                            ("dozen", "Dozen"),
                            ("each", "Each"),
                        ],
                        default="each",
                        max_length=16,
                    ),
                ),
                ("harvest_date", models.DateField()),
                (
                    "availability",
                    models.CharField(
                        choices=[
                            ("in-season", "In Season"),
                            ("year-round", "Year-round"),
                            ("unavailable", "Unavailable"),
                        ],
                        default="year-round",
                        max_length=16,
                    ),
                ),
                ("seasonal_dates", models.CharField(blank=True, max_length=64)),
                ("is_organic", models.BooleanField(db_index=True, default=False)),
                ("organic_certification", models.CharField(blank=True, max_length=120)),
                ("allergens", models.JSONField(blank=True, default=list)),
                ("image_url", models.URLField(blank=True)),
                ("stock", models.PositiveIntegerField(default=0)),
                ("food_miles", models.PositiveIntegerField(default=0)),
                ("is_surplus", models.BooleanField(default=False)),
                (
                    "surplus_discount",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "surplus_original_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                ("surplus_expires_at", models.DateTimeField(blank=True, null=True)),
                ("surplus_best_before", models.CharField(blank=True, max_length=64)),
                ("storage_tips", models.TextField(blank=True)),
                ("recipe_ideas", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="products",
                        to="catalog.category",
                    ),
                ),
                (
                    "producer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="catalog.producer",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["name"], name="catalog_pro_name_f603c0_idx"),
                    models.Index(
                        fields=["is_organic", "category"],
                        name="catalog_pro_is_orga_d4cb59_idx",
                    ),
                    models.Index(
                        fields=["availability"], name="catalog_pro_availab_1dcb5d_idx"
                    ),
                ],
            },
        ),
    ]
