# Generated by Django 5.2.11 on 2026-03-23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0002_productreview_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="productreview",
            name="moderation_reason",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="productreview",
            name="moderation_status",
            field=models.CharField(
                choices=[
                    ("published", "Published"),
                    ("pending", "Pending moderation"),
                    ("rejected", "Rejected"),
                ],
                default="published",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="productreview",
            name="producer_response",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="productreview",
            name="producer_response_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="productreview",
            index=models.Index(
                fields=["product", "moderation_status"],
                name="community_p_product_f888b3_idx",
            ),
        ),
    ]
